server:
  port: 8080
  servlet:
    context-path: /ShopEProduction

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/ShopEProduction"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true